package misc;

public class GameLoadException extends Exception {
	/**
	 * auto-generated by eclipse IDE
	 */
	private static final long serialVersionUID = -1172595943004178902L;

	public GameLoadException(String msg) {
		super(msg);
	}
}
