package misc;

public class HealthException extends Exception {
	/**
	 * auto-generated by eclipse IDE
	 */
	private static final long serialVersionUID = 2971499061880686192L;

	public HealthException(String msg) {
		super(msg);
	}
}
